FROM node:14-alpine3.10

# Install necessary dependencies for node-gyp and node-sass
RUN apk add --no-cache python3 make g++ && ln -sf python3 /usr/bin/python

RUN npm install -g http-server

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

CMD ["npm", "run", "dev"]
